services:
  postgres:
    image: postgres:15-alpine
    container_name: dis-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: disuser
      POSTGRES_PASSWORD: dispassword
      POSTGRES_DB: disdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dis-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
